config/routes.rb
Rails.application.routes.draw do
  resources :spring_places do
    collection do
      post 'import_csv'
    end
  end

  resources :spring_infos do
    collection do
      post 'import_csv'
    end
  end

  resources :osmotics

  resources :categories

  resources :areas

  resources :prefectures

end

app/models/spring_info.rb
class SpringInfo < ActiveRecord::Base
  belongs_to :spring_place, foreign_key: :spring_place_id
  belongs_to :category, foreign_key: :category_id
  belongs_to :osmotic, foreign_key: :osmotic_id

  def spring_place_str
    if self.spring_place
      self.spring_place.name
    end
  end

  def category_str
    if self.category
      self.category.name
    end
  end

  def osmotic_str
    if self.osmotic
      self.osmotic.name
    end
  end

  def check_csv(csv_file)
    require 'csv'
    require 'kconv'

    @valid_message = {}
    spring_infos =[]
    valid = true
    # csvファイルを受け取って文字列にする
    csv_text = csv_file.read

    csv_text = CSV.parse(Kconv.toutf8(csv_text))

    # ファイルの中身を先にチェックするよ
    csv_text.shift  # 先頭行を無視するよ
    line_number = 2
    csv_text.each do |row|
        logger.debug(row)
        spring_info = SpringInfo.new
        spring_info.spring_place_id   = row[0].to_i
        spring_info.category_id       = row[1]
        spring_info.quality_name      = row[2]
        spring_info.old_quality_name  = row[3]
        spring_info.temperature       = row[4]
        spring_info.pH                = row[5]
        spring_info.osmotic_id        = row[6]
        spring_info.discharge         = row[7]
        spring_info.metasilicic_acid  = row[8]
        spring_info.remarks           = row[9]
        spring_info.save!
#        unless spring_info.valid?
#          valid = false
#        end
      line_number += 1
    end
    return valid, spring_infos
  end

end

app/controllers/spring_infos_controller.rb
class SpringInfosController < ApplicationController
  before_action :set_spring_info, only: [:show, :edit, :update, :destroy]

  # GET /spring_infos
  # GET /spring_infos.json
  def index
    @spring_infos = SpringInfo.all
  end

  # GET /spring_infos/1
  # GET /spring_infos/1.json
  def show
  end

  # GET /spring_infos/new
  def new
    @spring_info = SpringInfo.new
  end

  # GET /spring_infos/1/edit
  def edit
  end

  # POST /spring_infos
  # POST /spring_infos.json
  def create
    @spring_info = SpringInfo.new(spring_info_params)

    respond_to do |format|
      if @spring_info.save
        format.html { redirect_to @spring_info, notice: 'Spring info was successfully created.' }
        format.json { render :show, status: :created, location: @spring_info }
      else
        format.html { render :new }
        format.json { render json: @spring_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spring_infos/1
  # PATCH/PUT /spring_infos/1.json
  def update
    respond_to do |format|
      if @spring_info.update(spring_info_params)
        format.html { redirect_to @spring_info, notice: 'Spring info was successfully updated.' }
        format.json { render :show, status: :ok, location: @spring_info }
      else
        format.html { render :edit }
        format.json { render json: @spring_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spring_infos/1
  # DELETE /spring_infos/1.json
  def destroy
    @spring_info.destroy
    respond_to do |format|
      format.html { redirect_to spring_infos_url, notice: 'Spring info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import_csv
    spring_info = SpringInfo.new
    if params[:csv_file].nil?
      redirect_to spring_infos_path, :notice => "アップロードファイルを選択して下さい。"
    else
      valid, spring_infos = spring_info.check_csv(params[:csv_file])
      logger.debug(valid)
      if valid
        logger.debug('save')
        redirect_to spring_infos_path, :notice => "更新が完了しました。"
      else
        logger.debug('not save')
        render :index
      end
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_spring_info
      @spring_info = SpringInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spring_info_params
      params.require(:spring_info).permit(:spring_place_id, :category_id, :quality_name, :old_quality_name, :temperature, :pH, :osmotic_id, :discharge, :metasilicic_acid, :remarks)
    end
end

app/helpers/spring_infos_helper.rb
module SpringInfosHelper
end

app/views/spring_infos/_form.html.erb
<%= form_for(@spring_info) do |f| %>
  <% if @spring_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spring_info.errors.count, "error") %> prohibited this spring_info from being saved:</h2>

      <ul>
      <% @spring_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :温泉地 %><br>
    <%= f.collection_select :spring_place_id, SpringPlace.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :quality_name %><br>
    <%= f.text_field :quality_name %>
  </div>
  <div class="field">
    <%= f.label :old_quality_name %><br>
    <%= f.text_field :old_quality_name %>
  </div>
  <div class="field">
    <%= f.label :temperature %><br>
    <%= f.text_field :temperature %>
  </div>
  <div class="field">
    <%= f.label :pH %><br>
    <%= f.text_field :pH %>
  </div>
  <div class="field">
    <%= f.label :osmotic_id %><br>
    <%= f.collection_select :osmotic_id, Osmotic.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :discharge %><br>
    <%= f.text_field :discharge %>
  </div>
  <div class="field">
    <%= f.label :metasilicic_acid %><br>
    <%= f.text_field :metasilicic_acid %>
  </div>
  <div class="field">
    <%= f.label :remarks %><br>
    <%= f.text_field :remarks %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spring_infos/edit.html.erb
<h1>Editing spring_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @spring_info %> |
<%= link_to 'Back', spring_infos_path %>

app/views/spring_infos/index.html.erb
<h1>Listing spring_infos</h1>
<h3>CSVアップロード</h3>
<div class="alert.alert-success">
  <%= form_tag import_csv_spring_infos_path, action: "import_csv", method: "post",multipart: true do %>
    <div class="field">
      <%= file_field_tag :csv_file %>
      <br />
    </div>
    <div class="actions">
      <%= submit_tag "CSVファイル取込" %>
    </div>
  <% end %>
</div>


<table class="table-bordered">
  <thead>
    <tr>
      <th>温泉地</th>
      <th>泉質</th>
      <th>泉質（詳）</th>
      <th>泉質（旧）</th>
      <th>泉温</th>
      <th>pH</th>
      <th>浸透圧</th>
      <th>湧出量</th>
      <th>メタケイ酸</th>
      <th>備考</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spring_infos.each do |spring_info| %>
      <tr>
        <td><%= spring_info.spring_place_str %></td>
        <td><%= spring_info.category_str %></td>
        <td><%= spring_info.quality_name %></td>
        <td><%= spring_info.old_quality_name %></td>
        <td><%= spring_info.temperature %></td>
        <td><%= spring_info.pH %></td>
        <td><%= spring_info.osmotic_str %></td>
        <td><%= spring_info.discharge %></td>
        <td><%= spring_info.metasilicic_acid %></td>
        <td><%= spring_info.remarks %></td>
        <td><%= link_to 'Edit', edit_spring_info_path(spring_info) %></td>
        <td><%= link_to 'Del', spring_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spring info', new_spring_info_path %>

app/views/spring_infos/new.html.erb
<h1>New spring_info</h1>

<%= render 'form' %>

<%= link_to 'Back', spring_infos_path %>

app/views/spring_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Area:</strong>
  <%= @spring_info.area_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @spring_info.name %>
</p>

<p>
  <strong>Quality name:</strong>
  <%= @spring_info.quality_name %>
</p>

<p>
  <strong>Old quality name:</strong>
  <%= @spring_info.old_quality_name %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @spring_info.temperature %>
</p>

<p>
  <strong>Ph:</strong>
  <%= @spring_info.pH %>
</p>

<p>
  <strong>Osmotic:</strong>
  <%= @spring_info.osmotic_id %>
</p>

<p>
  <strong>Discharge:</strong>
  <%= @spring_info.discharge %>
</p>

<p>
  <strong>Place:</strong>
  <%= @spring_info.place %>
</p>

<p>
  <strong>Transportation:</strong>
  <%= @spring_info.transportation %>
</p>

<p>
  <strong>Metasilicic acid:</strong>
  <%= @spring_info.metasilicic_acid %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @spring_info.remarks %>
</p>

<%= link_to 'Edit', edit_spring_info_path(@spring_info) %> |
<%= link_to 'Back', spring_infos_path %>