config/routes.rb
Rails.application.routes.draw do
  resources :spring_places do
    collection do
      post 'import_csv'
    end
  end

  resources :spring_infos do
    collection do
      post 'import_csv'
    end
  end

  resources :osmotics

  resources :categories

  resources :areas

  resources :prefectures

end

app/models/osmotic.rb
class Osmotic < ActiveRecord::Base
end

app/controllers/osmotics_controller.rb
class OsmoticsController < ApplicationController
  before_action :set_osmotic, only: [:show, :edit, :update, :destroy]

  # GET /osmotics
  # GET /osmotics.json
  def index
    @osmotics = Osmotic.all
  end

  # GET /osmotics/1
  # GET /osmotics/1.json
  def show
  end

  # GET /osmotics/new
  def new
    @osmotic = Osmotic.new
  end

  # GET /osmotics/1/edit
  def edit
  end

  # POST /osmotics
  # POST /osmotics.json
  def create
    @osmotic = Osmotic.new(osmotic_params)

    respond_to do |format|
      if @osmotic.save
        format.html { redirect_to @osmotic, notice: 'Osmotic was successfully created.' }
        format.json { render :show, status: :created, location: @osmotic }
      else
        format.html { render :new }
        format.json { render json: @osmotic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /osmotics/1
  # PATCH/PUT /osmotics/1.json
  def update
    respond_to do |format|
      if @osmotic.update(osmotic_params)
        format.html { redirect_to @osmotic, notice: 'Osmotic was successfully updated.' }
        format.json { render :show, status: :ok, location: @osmotic }
      else
        format.html { render :edit }
        format.json { render json: @osmotic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /osmotics/1
  # DELETE /osmotics/1.json
  def destroy
    @osmotic.destroy
    respond_to do |format|
      format.html { redirect_to osmotics_url, notice: 'Osmotic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_osmotic
      @osmotic = Osmotic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def osmotic_params
      params.require(:osmotic).permit(:name)
    end
end

app/helpers/osmotics_helper.rb
module OsmoticsHelper
end

app/views/osmotics/_form.html.erb
<%= form_for(@osmotic) do |f| %>
  <% if @osmotic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@osmotic.errors.count, "error") %> prohibited this osmotic from being saved:</h2>

      <ul>
      <% @osmotic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/osmotics/edit.html.erb
<h1>Editing osmotic</h1>

<%= render 'form' %>

<%= link_to 'Show', @osmotic %> |
<%= link_to 'Back', osmotics_path %>

app/views/osmotics/index.html.erb
<h1>Listing osmotics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @osmotics.each do |osmotic| %>
      <tr>
        <td><%= osmotic.name %></td>
        <td><%= link_to 'Show', osmotic %></td>
        <td><%= link_to 'Edit', edit_osmotic_path(osmotic) %></td>
        <td><%= link_to 'Destroy', osmotic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Osmotic', new_osmotic_path %>

app/views/osmotics/new.html.erb
<h1>New osmotic</h1>

<%= render 'form' %>

<%= link_to 'Back', osmotics_path %>

app/views/osmotics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @osmotic.name %>
</p>

<%= link_to 'Edit', edit_osmotic_path(@osmotic) %> |
<%= link_to 'Back', osmotics_path %>